# Generated by Django 3.0.5 on 2021-03-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt_dttm', models.CharField(max_length=20)),
                ('adstrd_code', models.CharField(max_length=20)),
                ('adstrd_nm', models.CharField(max_length=20)),
                ('mrhst_induty_cl_code', models.CharField(max_length=20)),
                ('mrhst_induty_cl_nm', models.CharField(max_length=20)),
                ('selng_cascnt', models.CharField(max_length=20)),
                ('salamt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adstrd_code', models.CharField(max_length=20)),
                ('adstrd_nm', models.CharField(max_length=20)),
                ('brtc_nm', models.CharField(max_length=20)),
                ('signgu_nm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoronaData',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_number', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('gugun', models.CharField(max_length=20)),
                ('overseas', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=50)),
                ('discharge', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fpopl',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('per_time', models.CharField(max_length=20)),
                ('age_range', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('gugun', models.CharField(max_length=10)),
                ('popl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GugunLocate',
            fields=[
                ('signgu_nm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
