# Generated by Django 3.0.5 on 2021-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adstrd_code', models.CharField(max_length=20)),
                ('adstrd_nm', models.CharField(max_length=20)),
                ('brtc_nm', models.CharField(max_length=20)),
                ('signgu_nm', models.CharField(max_length=20)),
            ],
        ),
    ]
