# Generated by Django 3.0.5 on 2021-03-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpopl',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('per_time', models.IntegerField()),
                ('age_range', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('gugun', models.CharField(max_length=10)),
                ('popl', models.IntegerField()),
            ],
        ),
    ]
