# Generated by Django 3.0.5 on 2021-03-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fpopl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt_dttm', models.CharField(max_length=20)),
                ('adstrd_code', models.CharField(max_length=20)),
                ('adstrd_nm', models.CharField(max_length=20)),
                ('mrhst_induty_cl_code', models.CharField(max_length=20)),
                ('mrhst_induty_cl_nm', models.CharField(max_length=20)),
                ('selng_cascnt', models.CharField(max_length=20)),
                ('salamt', models.IntegerField()),
            ],
        ),
    ]
