# Generated by Django 3.0.5 on 2021-04-01 01:00

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fpopl_bc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaWeight',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('weight_point', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DistWeight',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('weight_point', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FpoplWeight',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('weight_point', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('dist_weights', djongo.models.fields.ArrayField(model_container=api.models.DistWeight)),
                ('corona_weights', djongo.models.fields.ArrayField(model_container=api.models.CoronaWeight)),
                ('fpopl_weights', djongo.models.fields.ArrayField(model_container=api.models.FpoplWeight)),
            ],
        ),
    ]
