# Generated by Django 3.0.5 on 2021-03-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coronadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronadata',
            old_name='dong',
            new_name='gugun',
        ),
    ]
