# Generated by Django 3.0.5 on 2021-04-05 02:30

from django.db import migrations, models
import djongo.models.fields
import recomm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaWeight',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('weight_point', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DistanceData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('dist_weights', djongo.models.fields.ArrayField(model_container=recomm.models.DistWeight)),
            ],
        ),
        migrations.CreateModel(
            name='DistWeight',
            fields=[
                ('signgu_nm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weight_point', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FpoplWeight',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signgu_nm', models.CharField(max_length=20)),
                ('weight_point', models.FloatField()),
            ],
        ),
    ]
