# Generated by Django 3.0.5 on 2021-03-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaData',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_number', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
                ('overseas', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=50)),
                ('discharge', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
