# Generated by Django 3.0.5 on 2021-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=70)),
                ('nickname', models.CharField(max_length=30)),
                ('is_auth', models.BooleanField(default=False)),
            ],
        ),
    ]
