# Generated by Django 3.0.5 on 2021-04-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_search_searchlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='address',
            new_name='juso',
        ),
    ]
